In [1]:
!pip install numpy

In [4]:
import numpy as np

arr1 = np.array([1,2,3])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3]
<class 'numpy.ndarray'>
(3,)


In [6]:
arr2 = np.array([1,2,3])
arr2.reshape(1,3)

array([[1, 2, 3]])

In [7]:
arr2 = np.array([[1,2,3]])
arr2.shape

(1, 3)

In [8]:
arr2 = np.array([[1,2,3],[2,3,4]])
print(arr2)
print(arr2.shape)

[[1 2 3]
 [2 3 4]]
(2, 3)


In [10]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [11]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [12]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [13]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [14]:
arr = np.array([1,2,3,4,5])
print(np.sqrt(arr))

[1.         1.41421356 1.73205081 2.         2.23606798]
